Cargo.toml
This adds the repository URL to cargo manifest, so that it will
show up on crates.io.
=> cargo: add repository URL

src/base.rs, src/decoder.rs
This is a minor cleanup pass to avoid unnecessary cloning and
unwrapping in the decoder.
=> decoder: misc cleanups

benches/matrix_sparsity.rs, src/arraymap.rs, src/base.rs, src/constraint_matrix.rs, src/decoder.rs, src/encoder.rs, src/pi_solver.rs, src/rng.rs, src/symbol.rs
This performs a cleanup on encoder and decoder, to remove some redundant casts and bytes duplications.
=> codec: remove some casts and allocations

src/octets.rs
This simplifies the non-SIMD mulassign, making its safety invariants
explicit and documented.
=> mulassign/fallback: make safety invariants explicit

src/arraymap.rs
The request I made a few days ago. Figured .keys() could return a DoubleEnded Iterator instead of just an Iterator, which allows to iterate backwards over the keys.
=> .keys() returns a DoubleEndedIterator

src/decoder.rs
Hi,
First I'd like to say thank you for this amazing library ! I've been looking for a functional and fast fountain code library in Rust for a while. 
I've noticed a specific need I have in my use of your library: I process packets and get the resulting data in separate places. The use of the `decode` method on the `Decoder` object is impractical to me. I therefore divided it in two separate methods: one that mutates the Decoder by adding a new packet and one that just 'checks' if decoding is possible yet.
I hope it makes some sense.
=> Breaking up the decoding method in smaller single-purpose methods

src/constraint_matrix.rs, src/octet.rs
The gamma matrix was being generated incorrectly due to casting
(i - j) to u8 instead of wrapping it to 255 values
=> Fix generation of constraint matrix for 1698 and 8837 source symbols

Cargo.toml, src/arraymap.rs, src/base.rs, src/decoder.rs, src/encoder.rs, src/iterators.rs, src/matrix.rs, src/octet.rs, src/pi_solver.rs, src/sparse_matrix.rs, src/sparse_vec.rs, src/symbol.rs
This should make it possible to use serde to serialize and deserialize
encoders/decoders while they are in use.  This is makes it possible to
ship them between processes as needed.
=> feat: Derived serde::{Serialize, Deserialize} on all public types.

README.md
Approximately 1.5x faster for symbol counts over 250, and 2x faster over
5k symbols
=> Update benchmarks with 1.1.0 results

Makefile
This avoids monopolizing the CPU, since these tests use many threads and
run for hours
=> Set 'nice' on extended tests

src/base.rs
The maximum value in RFC6330 of 946270874880 is incorrect as
documented in errata id 5548
=> Fix max length assertion

src/base.rs, src/encoder.rs, src/lib.rs
Hi!
I now have a copy of the decoder implementation in my code with my additional get partial result function. For that to work i need to have access to the partition function or copy it as-well. I felt like it really belonged in the raptorq crate so in this pr i make it public.
I'm using the encoder from a c++ application through an ffi interface. I'm doing it in two phases where i first want to know the ObjectTransmissionInformation before i can calculate how many extra packets i want to generate. To make this easier i make the new method of OTI public and made the struct copy.
All of these changes are maybe not aligned with your vision for the reptorq crate and that is perfectly ok! I'm presenting them to you to see it you want them. If there is any subset that you want i can change …
=> Changes for my use case

src/gf2.rs
Old version of code used single index to index both `dest` and `src`. Since in general the length of `src` is not known beforehand to be less or equal to length of `dest`, the compiler had no other choice but to keep bounds checking related code. Moreover, since panic information includes information about index, the code has to process one `u32` per iteration.
Checking the length of `src` _before_ starting the loop lets the optimizer eliminate bounds checking and vectorise the loop, ultimately leading to better (at least, I hope so) performance.
[Assembly before and after the change](https://godbolt.org/z/fs4f33)
=> Avoid bounds checking in loop

README.md, src/matrix.rs, src/pi_solver.rs, src/sparse_matrix.rs
Previously we used column major ordering. Switch to row major to
optimize sequential access of rows which is much more common in the
first phase, and can also be used in the fourth phase
This improves performance by ~10% on large symbol counts
=> Optimize memory layout of dense U matrix

README.md, src/sparse_matrix.rs
This reduces the time spent in the fourth phase from ~6% of encoding
time to ~1%, according to perf, and improves overall throughput by 3-4%
on large symbol counts.
=> Optimize query_non_zero_columns()

README.md, src/iterators.rs, src/matrix.rs, src/util.rs
Switch to a single contiguous vector instead of vec of vecs
This improves performance by ~5%, especially for smaller symbol counts
=> Optimize DenseBinaryMatrix

Cargo.toml
This allows the package to be used on any Python version >= 3.6
=> Build Python package with abi3 support

src/pi_solver.rs
This is safe due to Errata 11, and speeds up performance by a couple
percent
=> Skip elimination in V section of A during first phase

README.md
The previous benchmarks were run with a faulty power supply which
artificially lowered the clock speed
=> Update Raspberry Pi 3 B+ benchmarks

src/decoder.rs, src/graph.rs
There was an off-by-one error in the initialization of storage for
connected components, such that if there were the same number of
connected components as nodes it would cause an index out of bounds
error
Fixes #120
=> Fix panic in graph traversal

src/decoder.rs, src/encoder.rs
Previously, we incorrectly assigned internal symbol IDs (ISIs) to the `PayloadId` of `EncodingPacket`s. According to RFC 6330, it should be the encoding symbol IDs (ESIs). This commit fixes this inconsistency.
BREAKING CHANGE: As the assignment of symbol IDs changes, encoding packets generated before this change cannot be decoded by the new version and vice-versa.
Closes #164
=> Fix symbol IDs assigned to encoding packets
